version: '3.8'

services:
  nginx:
    build:
      context: .
    image: nginx:brotli
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx
      - ./letsencrypt:/etc/letsencrypt
    network_mode: host
    restart: unless-stopped
